### ISSUE TITLE
Extend cubx-dependency-resolver to return resolved dependencyTree

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubx-dependency-resolver#2]
Adjust `cubx-dependency-resolver` to return resolved DependencyTree represented as JSON string.

@pwrinc: Add solution approach from RTE

**Acceptance criteria:**
- [x] The JSON representation of the resolved DependencyTree is printed out to stdout
- [x] Add parameter `-t`/`--type` to CLI accepting the values:
* `raw`: returns raw DependencyTree
* `resolved`: returns resolved Dependency Tree
* `list` (default): return ordered list of resources (analogous to usage in RTE)
* `wplist`: return list of webpackages only (without ressources)
- [x] Add parameter `-m`/`--mode` to CLI accepting the values (Note: this only applies if parameter `type` is set to value `list`:
* `prod` (default): Use only `prod` resources
* `dev`: Use only `dev` resources

**Comment by edwingamboa** [comment]
### Print resources list by default
![image](https://user-images.githubusercontent.com/5494773/40881761-2e1585d8-6695-11e8-8046-692777d59c3f.png)

### Print resolved depTree
![image](https://user-images.githubusercontent.com/5494773/40881770-68590bd4-6695-11e8-930f-b842fc5f302c.png)

### Print raw depTree
![image](https://user-images.githubusercontent.com/5494773/40881774-8abb7400-6695-11e8-8541-07db6effe4d2.png)

**Comment by edwingamboa** [comment]
### Print wplist
![image](https://user-images.githubusercontent.com/5494773/41114320-b61da48a-6a49-11e8-9fba-9d51db744c84.png)

**Comment by pwrinc** [comment]
@edwingamboa: Hi Edwin. I tried to test the `cubx-dependency-resolver` installing it globally with `npm install -g`. But I was not able to call `cubx-dependency-resolver` in bash. I recognized that there was no `cubx-dependency-resolver.cmd` created in `C:\Users\[User]\AppData\Roaming\npm` like for all other globally installed packages. That seems to be the reason, why I can't use it. Can you please check. how to configure an npm package to provide such a cmd to use it globally when installing it using `npm install -g`? 

**EDIT:**
I think the issue of the missing executable comes because of the absence of the `bin` property in package.json (see https://docs.npmjs.com/files/package.json#bin) for details

**Comment by edwingamboa** [comment]
@pwrinc the released version of cubx-dependency-resolver is not updated, it was 15 days ago, and it has the problem you mention (bin property is missing). However, the updated code is on develop branch. After cloning the repo and checking out to develop branch, you can test it using the npm-link command (https://docs.npmjs.com/cli/link) to make it available from CLI.

**Comment by pwrinc** [comment]
@edwingamboa: I reviewed the npm module and it looks good :-) Nevertheless I do have a questions regarding using parameter `-t` with value `wplist`: Is the returned list of webpackages based on the `raw` or the resolved `tree`? Maybe we can discuss in our today weekly call.

**Comment by edwingamboa** [comment]
@pwrinc It uses the resolved tree.
